### ISSUE TITLE
Cannot connect to steam

### ISSUE THREAD

**Issue by blizzard2023** [Grover-c13/MultiAdmin#1]
Hi,

So I tried doing everything in the instructions, and the console gives me the "Cannot connect to steam" error.

**Comment by Grover-c13** [comment]
Hi, 

Like the normal server software you need to have steam running.

If this is not the issue please provide an output_log.txt file from multiadmin (servers/<config>/logs)

**Comment by Grover-c13** [comment]
Just realised you might be missing steam_appid.txt in your root folder!

please place this next to SCPSL.exe
[steam_appid.txt](https://github.com/Grover-c13/MultiAdmin/files/1682640/steam_appid.txt)

**Comment by blizzard2023** [comment]
Hi, thanks that works! However, now my server name says "auto". I've posted my configuration file below:
https://pastebin.com/askBhUir

**Comment by blizzard2023** [comment]
[2018-01-31_13_18_output_log.txt](https://github.com/Grover-c13/MultiAdmin/files/1682857/2018-01-31_13_18_output_log.txt)
