### ISSUE TITLE
Command RECONNECTRS does not exist!

### ISSUE THREAD

**Issue by laserman367** [Grover-c13/MultiAdmin#100]
![3w8c8mb 1](https://user-images.githubusercontent.com/36745405/36615701-789bc47a-18e1-11e8-997b-419171e317ef.png)

**Comment by Grover-c13** [comment]
So two things happened:
My version checker for multiadmin isnt work properly, will have to fix. I also uploaded the wrong ServerMod version, it was actually 1.4, 1.5.2 is uploaded correctly now.
