### ISSUE TITLE
multiple scps seems not work

### ISSUE THREAD

**Issue by ShingekiNoRex** [Grover-c13/MultiAdmin#104]
Here is some of my config
team_respawn_queue = 400000400000400000400000400000;
SCP173_Amount = 10;
SCP049_Amount = 10;
SCP106_Amount = 5;

**Comment by Grover-c13** [comment]
Currently the settings are case sensitive, should be all uppercase. Next version of smod will be case insensitive.

**Comment by Grover-c13** [comment]
case sensitivity should be fixed in https://github.com/Grover-c13/MultiAdmin/releases/tag/SM1.6

Reopen if its still an issue :)
