### ISSUE TITLE
SCP106_cleanup doesn't work properly (still)

### ISSUE THREAD

**Issue by realmbmc** [Grover-c13/MultiAdmin#105]
SCP106_cleanup doesn't do anything at SM 1.6

**Comment by laserman367** [comment]
I asked grover about it and he said he made it check for SCP106_CLEANUP isntead of SCP106_cleanup, but even with that it doesn't seem to work for me so idk

**Comment by TheKigen** [comment]
It looks for SCP106_CLEANUP being set to "yes".  If its set to anything other than "yes" it doesn't work.

**Comment by realmbmc** [comment]
GAME SETTINGS:
minimum_MTF_time_to_spawn = 360;
maximum_MTF_time_to_spawn = 500;
ci_respawn_percent = 30;
ci_on_start_percent = 30;
team_respawn_queue = 40444430444443104421;
server_forced_class = -1; (-1 = random)
map_seed = -1; (-1 = random)
intercom_cooldown = 120;
intercom_max_speech_time = 30;
auto_round_restart_time = 30;
friendly_fire = true;
max_players = 20;
RESTART_EVERY_NUM_ROUNDS = 10;
SCP173_HP = 5000;
SCP049-2_HP = 700;
nuke_disable_cooldown = 80;
SCP106_CLEANUP = yes;
RESTART_LOW_MEMORY = 1040;
NUKE_MIN_TIME = 120;
SM_TRACKING = false;
SCP049_DISABLE = no;
SCP079_DISABLE = yes;
SCP106_DISABLE = no;
SCP173_DISABLE = no;
SCP457_DISABLE = yes;

///////////////////////////////////

THESE SETTINGS REQUIRES THE GAME TO RESTART:
server_ip = auto;
server_name =xxx;
ban_database_folder = [appdata]/SCP Secret Laboratory/Bans;
administrator_password = welcometohell-pass123;
port_queue = 7777;
serverinfo_mode = info; (disabled - off, info - on)
serverinfo_pastebin_id = xxx;

Still doesn't work

**Comment by Grover-c13** [comment]
yeah so i was removing it by checking the location, but it turns out initial items spawn at 0, 200, 0, so that didnt work :/

Ive gone to a third method now which seems to work. Gonna test it a bit, but seems like its working.

**Comment by realmbmc** [comment]
Awesome! Thanks Grover-c13 for your work!
