### ISSUE TITLE
Anti-cheat suggestion and issue

### ISSUE THREAD

**Issue by realmbmc** [Grover-c13/MultiAdmin#108]
if nickname = "" OR hwid = ""
conn.closeconnection to player

ALSO
I've tested myself and I still can spawn clientside items using GIVE command on ANY server with a deleted check from assembly dll. GameConsole class. So the items handling isn't serverside (probably until clientside update)

**Comment by Grover-c13** [comment]
We cant really stop client side GIVES at the moment (inventory is pretty much client side), we can only stop them dropping them/spawning tons of items etc/shooting guns they dont have. 

Im looking into stopping doors too if they try to open it with a card they shouldn't have, making effectively spawning items client side useless as none of them will really function.

**Comment by Grover-c13** [comment]
Also name has been done, coming next version :)

**Comment by realmbmc** [comment]
Please check HWID variable too. Cheaters can replace HWID variable.

**Comment by realmbmc** [comment]
Also cheaters can edit memory to have infinite ammo without reload to any weapons. They can edit weapon's fire type, shooting speed and damage.
Also they can edit AmmoBox memory easily. I can describe more if you want. I've reversed game a bit (only for researching purposes).

**Comment by TheKigen** [comment]
Hi,

I've been the one primarily writing the anti-cheat work.  I am aware of all the issues you've brought up.  Some of them we cannot fix directly.  Like a client sending a fake HWID.  This is just not possible to fix.  We can check if it is of the appropriate size.  But they'll just fake it.  

As far as infinite ammo, tracking ammo usage is a future goal.  It would be easier once everything is server-sided.  Then none of this would be a concern.   There are a lot of other things you are unaware of.  But changing the weapon's fire type or damage only affects the client's perception of what's going on.

**Comment by realmbmc** [comment]
Somehow cheaters now managed to use admin console's commands without even logging to admin panel.
We've seen today player without nickname and hwid changing everyone's class to 049-2
