### ISSUE TITLE
Suggestion - Custom Default Equipment for Each Role

### ISSUE THREAD

**Issue by ShingekiNoRex** [Grover-c13/MultiAdmin#109]
Date:
26/02/2018

Feature:
Custom Default Equipment for Each Role

Reason:
Since the command "giveall" is available, I hope the server can automatically give all class-d's some items like flashlight when they spawn.

**Comment by realmbmc** [comment]
Nice idea!
Also randomized chance of spawning each item (["class_name", chance_integer]) would be awesome.
