### ISSUE TITLE
RESTARTNEXTROUND cause an error

### ISSUE THREAD

**Issue by realmbmc** [Grover-c13/MultiAdmin#11]
After command exec this a new server starts but old server doesn't close. It starts spamming this error:

> [21:55:43] Retrying.
> [21:55:43] Message printer warning: Could not open file SCPSL_Data\Dedicated\1517942782\sl125.mapi. Make sure that MultiAdmin.exe has all necessary read-write permissions.

Delayed restart in number of round works fine.

**Comment by Grover-c13** [comment]
Should hopefully be fixed in the new version, let me know if its still occurring.
