### ISSUE TITLE
Server List

### ISSUE THREAD

**Issue by blizzard2023** [Grover-c13/MultiAdmin#111]
It seems after updating to the latest version of Multadmin and Servermod my server will no longer show on the server list. Not only that happens, but friendly fire seemed to turn itself on and the admins cannot login using the admin password.

**Comment by Grover-c13** [comment]
Post a screenshot of your console after it starts up

**Comment by blizzard2023** [comment]
https://gyazo.com/56afb2b66f130bbae666d9d31017b6fa

**Comment by blizzard2023** [comment]
Also my output log: https://pastebin.com/EtEyALrH

**Comment by blizzard2023** [comment]
It seemed to be an issue with the most recent servermod/multiadmin update. I reverted to update 1.5, but now I have people spawning as more than one of the same SCP.

**Comment by Grover-c13** [comment]
It probably is showing up with a default name, try removing the
"// server_name can stuff up the cfg reader depending on its contents, so keep it down the bottom."
line if you have it.

If not post your config sans password and ill take a look

**Comment by blizzard2023** [comment]
I did not have that in my .cfg

I have to use ServerMod 1.5.2. I can't use the most recent otherwise my server will have a crap load of errors such as:

- Admins cannot use the admin panel (Can't login)
- Server name appears as "Unnamed Server" even though it's set in the server.cfg
- Friendly Fire is turn on (even though it's set in the server.cfg)

**Comment by Grover-c13** [comment]
Post your config

**Comment by blizzard2023** [comment]
I don't have it anymore. I removed it because it wasn't working. Like I said I'm using 1.5.2 now.

**Comment by blizzard2023** [comment]
Here is my config: https://pastebin.com/JqNjY8ne

I really would like this to be solved as I need the item tracker.

**Comment by blizzard2023** [comment]
@Dankrushen I am talking about how the server is using all default variables for my cvars.

**Comment by Dankrushen** [comment]
Have you tried validating the server files? Just by looking at the logs nothing seems too off, so I don't know what could be causing the problem...

**Comment by Dankrushen** [comment]
Have you tried validating the server files? Just by looking at the logs nothing seems too off, so I don't know what could be causing the problem...
