### ISSUE TITLE
Item spawning abuse

### ISSUE THREAD

**Issue by E-v-o** [Grover-c13/MultiAdmin#112]
Just a heads up really, a few people now have managed to spawn in items since the last update. From what I can tell it's mostly standard memory editing. I believe it's still possible to technically cheat by "picking up" the item instead of giving it to yourself, because if you pick it up then it would become verified?

Either way, I've added some basic checks and will post back result if anything actually helps, I thought I'd give you a heads up ASAP so you're at least aware of it.

**Comment by Grover-c13** [comment]
Hmm interesting, the would get around it i think. But next game version items are full server side so hopefully it wont be an issure anymore.

**Comment by E-v-o** [comment]
Perfect that's good to hear!

In the end after our discussion on Discord I went ahead and added the AntiFaker check, it counts how many times it returns a player to the previous position in 30 seconds and if it's more than 10 it gives then a 1 day ban. It's only banned one player so far but it might be worth including, doesn't seem to have any performance issues either!

**Comment by E-v-o** [comment]
@Grover-c13 Another one to look out for, this one is becoming really annoying. A few players have made it so the round end screen has a bunch of 1's, worth thing is the round restarts after something like 6 days.

https://media.discordapp.net/attachments/418528342610804746/419635400731131925/unknown.png?width=1024&height=640

They are also making everyone in the game (dead players mainly) zombies and running around with items as SCP's. The standard spawning cheaters aren't a huge issue but this is a little crazy...
