### ISSUE TITLE
Difficulties in setting up a development environment for MultiAdmin and ServerMod

### ISSUE THREAD

**Issue by sappykun** [Grover-c13/MultiAdmin#117]
Hi,
I spent a good chunk of yesterday trying to set up a working environment for MultiAdmin and Servermod.  I am familiar with C# and Visual Studio, but I am new to Unity and Monodevelop.

I was able to open the MultiAdmin.sln file found [here](https://github.com/Grover-c13/MultiAdmin/tree/master/mutliadmin) using Visual Studio and compile the executable just fine, but I am having trouble setting up an environment to generate the Assembly-CSharp.dll file for Servermod.

I made a new project in Unity and added the contents of [server_mod](https://github.com/Grover-c13/MultiAdmin/tree/master/server_mod) as scripts, but some of these scripts have dependencies on various Unity store assets such as [Post Processing Stack](https://assetstore.unity.com/packages/essentials/post-processing-stack-83912) and [Dissonance](https://assetstore.unity.com/packages/tools/audio/dissonance-voice-chat-70078); I installed the former without issue, but the latter costs $70 USD.  Without resporting to piracy, I am not too sure where to progress from here, or even if what I am doing is correct.

Would it be possible for Grover or someone else who has gotten this to work to create a quick guide or list of prerequesites to get the environment up and running?
Also, is there a better means of contacting Grover other than via Github?  Maybe email or IRC?

Thanks.

**Comment by Grover-c13** [comment]
You can get me on our discord now or the main SCP-SL discord. otherwise Grover.c13@gmail.com

Anyway i need to remove the "servermod" directory from the repo, its misleading. We are actually working from a different repo now. Before i was patching in changes using dnSpy (hence partial parts of code etc), but not we work from a full decompile we have chosen to not make public right now.
