### ISSUE TITLE
Suggestion: Custom Server Roles

### ISSUE THREAD

**Issue by E-v-o** [Grover-c13/MultiAdmin#118]
So with the latest update, as it's using role ids and sending it to the clients, any chance we could have custom roles added? Would love to add a players name in the config, it checks if they are logged into remoteadmin + has name then gives role 4.

Would also be handy to have a donator role, not sure how that could be done though, perhaps hwid or IP?

**Comment by TheKigen** [comment]
No, not currently.  The Server Roles information is stored in the shared assets files and we cannot edit it.  Plus if we could the client would have to download those edits.
