### ISSUE TITLE
RemoteAdmin not working

### ISSUE THREAD

**Issue by E-v-o** [Grover-c13/MultiAdmin#119]
I know you've probably had a bunch of messages already, but at least with it raised here people can look before spamming you and see any progress/issues.

Issue:
Unable to retrieve player list from the server.
https://i.imgur.com/zxCW3c8.png

**Comment by SqTH** [comment]
This has to be the highest priority

**Comment by Dankrushen** [comment]
I'm looking into it right now

**Comment by TheKigen** [comment]
This has been fixed.

**Comment by SqTH** [comment]
Thanks alot!!
