### ISSUE TITLE
Server creates lobby but never waits for new players

### ISSUE THREAD

**Issue by ADrySoldier** [Grover-c13/MultiAdmin#12]
The first server that auto starts up waits for players and then starts regularly once sufficient have joined, but any server after the first simply states "Server starting at port 777X",  and never continues to say "Waiting for Players.." or "New round has been started."

**Comment by Grover-c13** [comment]
Cant recreate locally, can you post your server log for the one thats not starting?

**Comment by ADrySoldier** [comment]
[2018-02-06_19_53_output_log.txt](https://github.com/Grover-c13/MultiAdmin/files/1701393/2018-02-06_19_53_output_log.txt)
[2018-02-06_19_42_output_log.txt](https://github.com/Grover-c13/MultiAdmin/files/1701394/2018-02-06_19_42_output_log.txt)
[Uploading 2018-02-06_19_48_output_log.txt…]()

**Comment by ADrySoldier** [comment]
Last three logs I've tried from the second server. I also have a third server that does the same thing the second server does.

**Comment by Grover-c13** [comment]
Post the config of your second and third server

**Comment by ADrySoldier** [comment]
![untitled](https://user-images.githubusercontent.com/16652023/35896653-35b49302-0b8b-11e8-9e9b-f658cd824bce.png)
Top left is server one, top right is server two, bottom is server three

**Comment by Grover-c13** [comment]
post the config.txt files please

**Comment by ADrySoldier** [comment]
Server 1: 

GAME SETTINGS:
minimum_MTF_time_to_spawn = 280;
maximum_MTF_time_to_spawn = 350;
ci_respawn_percent = 35;
ci_on_start_percent = 25;
team_respawn_queue = 40343140314414041340134134;
server_forced_class = -1; (-1 = random)
map_seed = -1; (-1 = random)
intercom_cooldown = 10;
intercom_max_speech_time = 60;
auto_round_restart_time = 20;
friendly_fire = false;

///////////////////////////////////

THESE SETTINGS REQUIRES THE GAME TO RESTART:

MUTLIADMIN SETTINGS:
manual_start = false;
start_config_on_full=server_two_config_folder;
shutdown_once_empty=-1;
restart_every_num_rounds=100;

SERVERMOD SETTINGS:
NO_SCP079_FIRST = true;
SCP049_HP = 1200;
SCP049-2_HP = 400;
SCP079_HP = 100;
SCP106_HP = 700;
SCP457_HP = 700;
SCP173_HP = 2000;
max_players = 20;


// server_name can stuff up the cfg reader depending on its contents, so keep it down the bottom.
server_name = <color=blue>[EST][US]</color><color=red><b><i> SCP: Secure, Cassio, Protect #1</i></b></color><color=blue>[$full_player_count]</color><color=red><i><b> Join discord.gg/pJDAtC2 | FF = OFF</b></i></color>;
server_ip = 98.217.215.24;
administrator_password = gunny;
ban_database_folder = [appdata]/SCP Secret Laboratory/Bans;
port_queue = 7777;
serverinfo_mode = info; (disabled - off, info - on)
serverinfo_pastebin_id = 7wV681fT;
 
Server 2:

GAME SETTINGS:
minimum_MTF_time_to_spawn = 280;
maximum_MTF_time_to_spawn = 350;
ci_respawn_percent = 35;
ci_on_start_percent = 25;
team_respawn_queue = 40343140314414041340134134;
server_forced_class = -1; (-1 = random)
map_seed = -1; (-1 = random)
intercom_cooldown = 10;
intercom_max_speech_time = 60;
auto_round_restart_time = 20;
friendly_fire = true;

///////////////////////////////////

THESE SETTINGS REQUIRES THE GAME TO RESTART:

MUTLIADMIN SETTINGS:
manual_start = false;
start_config_on_full=;
shutdown_once_empty=-1;
restart_every_num_rounds=100;

SERVERMOD SETTINGS:
NO_SCP079_FIRST = true;
SCP049_HP = 1200;
SCP049-2_HP = 400;
SCP079_HP = 100;
SCP106_HP = 700;
SCP457_HP = 700;
SCP173_HP = 2000;
max_players = 20;


// server_name can stuff up the cfg reader depending on its contents, so keep it down the bottom.
server_name = <color=blue>[EST][US]</color><color=red><b><i> SCP: Secure, Cassio, Protect #2</i></b></color><color=blue>[$full_player_count]</color><color=red><i><b> Join discord.gg/pJDAtC2 | FF = ON</b></i></color>;
server_ip = 98.217.215.24;
administrator_password = gunny;
ban_database_folder = [appdata]/SCP Secret Laboratory/Bans;
port_queue = 7778;
serverinfo_mode = info; (disabled - off, info - on)
serverinfo_pastebin_id = 7wV681fT;
 
Server 3:

GAME SETTINGS:
minimum_MTF_time_to_spawn = 280;
maximum_MTF_time_to_spawn = 350;
ci_respawn_percent = 35;
ci_on_start_percent = 25;
team_respawn_queue = 403431403144140413401;
server_forced_class = -1; (-1 = random)
map_seed = -1; (-1 = random)
intercom_cooldown = 10;
intercom_max_speech_time = 60;
auto_round_restart_time = 20;
friendly_fire = false;

///////////////////////////////////

THESE SETTINGS REQUIRES THE GAME TO RESTART:

MUTLIADMIN SETTINGS:
manual_start = false;
start_config_on_full=server_one_config_folder;
shutdown_once_empty=-1;
restart_every_num_rounds=15;

SERVERMOD SETTINGS:
NO_SCP079_FIRST = true;
SCP049_HP = 1200;
SCP049-2_HP = 400;
SCP079_HP = 100;
SCP106_HP = 700;
SCP457_HP = 700;
SCP173_HP = 2000;
max_players = 20;


// server_name can stuff up the cfg reader depending on its contents, so keep it down the bottom.
server_name =  <color=blue>[EST][US]</color><color=red><b><i> SCP: Secure, Cassio, Protect #1</i></b></color><color=blue>[$full_player_count]</color><color=red><i><b> Join discord.gg/pJDAtC2 | FF = ON</b></i></color>
server_ip = auto;
administrator_password = gunny;
ban_database_folder = [appdata]/SCP Secret Laboratory/Bans;
port_queue = 7779;
serverinfo_mode = disabled; (disabled - off, info - on)
serverinfo_pastebin_id = 7wV681fT;

**Comment by TheKigen** [comment]
I had the same issue when I updated to ServerMod to 1.1 from 0.6.  It'd start but never show up in any server list.  No changes to the config.txt during the upgrade.

**Comment by ADrySoldier** [comment]
Well, the thing is, all three of my servers show up on the list, but you just can't connect them and if you try to you are just stuck in a static camera looking at the bottom of a Class D cell.

**Comment by Grover-c13** [comment]
Cant recreate, but ive just noticed you seem to be using an old version of servermod? Since 0.6 it will print a ServerMod version x.x to the console. Can you tell me what version you are using so i can try to recreate?

**Comment by Grover-c13** [comment]
@TheKigen there was an accidental bug that disabled the verification check in the previous version (that i use for testing), wasnt intended to be their on release. So you will have to follow the verification process

**Comment by ADrySoldier** [comment]
If I'm using an old version couldn't I just update it and then ? Or do you still want me to tell you the version anyways so you can recreate? If so, how do I check the version?

**Comment by ADrySoldier** [comment]
I actually just download the Assembly-CSharp.dll last night so I believe it's the latest version you have uploaded

**Comment by Grover-c13** [comment]
Yeah thats right, currently the Read me links to 0.1, so if you got it from there it may not be right. This is the latest server mod https://github.com/Grover-c13/MultiAdmin/releases/tag/SM1.1

Try downloading and installing that. Make sure you place it in 
SCPSL_Data\Managed\ and overwrite the original.

**Comment by ADrySoldier** [comment]
I've installed it, testing if the servers work now

**Comment by ADrySoldier** [comment]
All three servers still just stay at "Server starting at port 777X", but I just noticed that all three servers cause my CPU to go up to 99% constantly, do you think it's just because the computer doesn't have the processing power to handle anything more than one server?

**Comment by ADrySoldier** [comment]
I got a new command line after the server starting at port 777X:

[00:48:18] at RadioInitializator.Start () [0x00000] in <filename unknown>:0

**Comment by Grover-c13** [comment]
The error shouldnt be related. The game does start based of the logs, it just never gets to the stage it needs to.

Can you try this debug version? if there is an issue where i think there is it should spam WAITING FOR HOST in console.
[Assembly-CSharp.zip](https://github.com/Grover-c13/MultiAdmin/files/1701981/Assembly-CSharp.zip)

**Comment by ADrySoldier** [comment]
![untitled](https://user-images.githubusercontent.com/16652023/35901949-4f1e8a52-0ba7-11e8-9cd7-dbd5b87e86cc.png)

First server spams it, second server stops at the ports, third server didn't start up at all but just opened the console.

**Comment by Grover-c13** [comment]
Can you restart and do it again? just want to see if it swaps between servers. Also you have the cursor locked on the third console :P right click on it.

**Comment by ADrySoldier** [comment]
Oh lol you were right the cursor was locked. I'm dumb. The third console goes as far as the second does. Restarting now.

**Comment by ADrySoldier** [comment]
Second test is the same as last time, first server spams waiting for host while the other two are stuck on server starting at port 777X

**Comment by Grover-c13** [comment]
Hmm. first server shouldn't be spamming, very weird.  Can you try this debug version now? ive turned on advanced logging. should show any errors in the output_log now. Please attach them.
[Assembly-CSharp.zip](https://github.com/Grover-c13/MultiAdmin/files/1702041/Assembly-CSharp.zip)

**Comment by ADrySoldier** [comment]
This time all three of them were stuck on the starting server port 777X

Server 1: 
[2018-02-07_02_00_output_log.txt](https://github.com/Grover-c13/MultiAdmin/files/1702065/2018-02-07_02_00_output_log.txt)

Server 2:
[2018-02-07_02_01_output_log.txt](https://github.com/Grover-c13/MultiAdmin/files/1702066/2018-02-07_02_01_output_log.txt)

Server 3: 
[2018-02-07_02_02_output_log.txt](https://github.com/Grover-c13/MultiAdmin/files/1702068/2018-02-07_02_02_output_log.txt)

**Comment by Grover-c13** [comment]
Damn nothing special in them :(

Does your console now print "started server on port xxxx" after the first port message?

Also could i suggest you verify integrity of game files and reinstall servermod.

**Comment by ADrySoldier** [comment]
First it says "Server started on port 7777", and then after it creates the steam lobby and loads the level and chans the configs, the last message displayed is "Server starting at port 7777", which afterwords I assume it's supposed to say "Waiting for players".

I'll just put my server files off to the side and reinstall the whole damn game, can I have the EXACT links of the correct servermod and correct multiadmin so there's no possible way I can screw it up?

**Comment by ADrySoldier** [comment]
![untitled](https://user-images.githubusercontent.com/16652023/35905208-3e940d3a-0bb4-11e8-9c9d-cd16f23d1913.png)
 I redid everything and it still has the same problem.

**Comment by ADrySoldier** [comment]
I let the servers sit for about 20 minutes, and they are actually working now.
![untitled](https://user-images.githubusercontent.com/16652023/35905928-d75011b6-0bb6-11e8-8d14-c72b18203313.png)

Thanks for your help, I have let them sit for over an hour before with no results so something must've been done to finally make them work. It seems it takes 15 minutes for the third server to even begin to load up and accept players. Is it possible to reset one server, such as a third, without resetting the second and third so there is no need to restart all three everytime one crashes? Thanks again for your help.

**Comment by Grover-c13** [comment]
if one crashes it should autostart, but in case of an unrecovable case you just close one and type new <config> to start it again.
