### ISSUE TITLE
Remote admin is still seems to be laggy sometimes

### ISSUE THREAD

**Issue by realmbmc** [Grover-c13/MultiAdmin#120]
Much less laggy but still refuses to do anything (force class for example) using remote admin.
I've updated servermod to 1.7 (reuploaded one)

**Comment by TheKigen** [comment]
What is your ping to the server you are trying to use it from and how loaded is the box its running on?

**Comment by realmbmc** [comment]
Our dedicated server is loaded for ~40% CPU and uses ~4gb of RAM of maximum 16gb.
Ping is 55-65ms
