### ISSUE TITLE
SCP-914 doesn't work with SM 1.7

### ISSUE THREAD

**Issue by Barna13** [Grover-c13/MultiAdmin#121]
Hello, 914 does not work anymore when I install SM 1.7, thank you.

**Comment by TheKigen** [comment]
Please do a app_update validate on your server.

914's info is loaded from the shared asset files.

**Comment by realmbmc** [comment]
It works ok. I can comfirm.

**Comment by Barna13** [comment]
weird I did 'verify integrity of game files' it took me out SM 1.7 and 914 worked, but as soon as I reinstalled SM 1.7.2, 914 did not work anymore.

**Comment by Dankrushen** [comment]
As an update for anyone looking into it, it seems that the SCP914 object may be null and is never set to any value, I'll continue to look into this later today (probably in 2-3 hours).

**Comment by Dankrushen** [comment]
I haven't changed anything with 914 but my server just started working with 914, so let me know if you still have the issue with the new update to SCP: SL

**Comment by Barna13** [comment]
It works thanks!
