### ISSUE TITLE
Can't use items with servermod

### ISSUE THREAD

**Issue by DesaeverSiebe** [Grover-c13/MultiAdmin#123]
Basically, keycards and guns don't work at all. 
Guns can pretend to shoot, and hitmarkers appear, but you can't reload it or run out of ammo and it deals no damage & bulletholes don't appear.
Keycards say they don't have the access required, even if they do.
Ammo boxes allow you to change ammo amount & cycle through the types, but you can't drop ammo.
Grenades seem to still be able to be thrown, and apparently the explosion appears, since I've seen people react to it.

According to other people, you're not holding anything even though on your side you'll have your gun or your keycard out. I've had this problem the last like 3 servermod versions, but I thought it was the base game. However whenever I'm not using servermod, it seems to work fine

**Comment by TheKigen** [comment]
Are you using ServerMod as on your client?

**Comment by DesaeverSiebe** [comment]
Yes, am I really forced to have a separate folder to host with? It seemed to work fine to use as client as well before these last 3 versions

**Comment by TheKigen** [comment]
Please use a separate install for now.
