### ISSUE TITLE
Suggestion: auto Remove ragdolls and dropped item 

### ISSUE THREAD

**Issue by wackod** [Grover-c13/MultiAdmin#124]
too many dead bodys and dropped item by dead player is really lag and crash server
today i got a 60 MINS round  and scp kill 98 players then server lag  and then server crash

**Comment by ShingekiNoRex** [comment]
Its already a feature.
Add these to your config:
RAGDOLL_CLEANUP
ITEM_CLEANUP

**Comment by Dankrushen** [comment]
Already implemented, as ShingekiNoRex has said, there's `RAGDOLL_CLEANUP` and `ITEM_CLEANUP` options.
