### ISSUE TITLE
Nuke time and new weight system

### ISSUE THREAD

**Issue by Barna13** [Grover-c13/MultiAdmin#129]
Hello, The command NUKE TIME does not work with the new warhead, I also had a suggestion for the new system of weight, to be able to choose the rate of increase or decrease example: smart_class_picker_class_ <Class 4> _weight_decrease = 3, thanks.

**Comment by Dankrushen** [comment]
The ability to choose the rate of increase or decrease works almost exactly like that, you'd use `smart_class_picker_class_4_weight_decrease = 3`

**Comment by Dankrushen** [comment]
PS. Don't use the `smart_class_picker` option right now, that feature is really bugged and will most likely crash your server every few rounds, the reason to why that happens is yet to be figured out.

**Comment by Barna13** [comment]
Ok thanks a lot.

**Comment by Dankrushen** [comment]
Smart Class Picker should no longer be broken
