### ISSUE TITLE
Unhandled Exception: System.ArgumentOutOfRangeException: Length cannot be less than zero. Parameter name: length    at System.String.Substring(Int32 startIndex, Int32 length)    at MultiAdmin.Config.Reload()    at MutliAdmin.Program.StartHandleConfigs(String[] args)    at MutliAdmin.Program.Main(String[] args)

### ISSUE THREAD

**Issue by BaconSeaner** [Grover-c13/MultiAdmin#135]

**Comment by skyehosting** [comment]
I've been having the same issue. Still no luck fixing.
Error [here](https://gyazo.com/5e07aebab93aa48366fcec6e41052b9b)

**Comment by MrUniverseAP** [comment]
use the config provided by multiadmin

**Comment by Dankrushen** [comment]
Should be fixed in the next release, make sure your config isn't messed up because that would only happen if your config had a missing value.
