### ISSUE TITLE
Needs update!

### ISSUE THREAD

**Issue by FiveSeven7** [Grover-c13/MultiAdmin#14]
The game developer released the update and now this version does not work

**Comment by realmbmc** [comment]
Even MultiAdmin doesn't work correctly. But I think we should wait more time till actual game developers fixed memory leak and other issues. Currently server is crashing and there are alot of bugs with map generator.

**Comment by Grover-c13** [comment]
MutliAdmin is working fine as far as i can tell on my servers. I have a version of servermod, just waiting to test it on my server.

**Comment by Grover-c13** [comment]
https://github.com/Grover-c13/MultiAdmin/releases/tag/SM1.2

Ill be updating MultiAdmin in the next few days.
