### ISSUE TITLE
Game Issue: HWID calculation is wrong

### ISSUE THREAD

**Issue by realmbmc** [Grover-c13/MultiAdmin#142]
HWID is the same for certain players leading to their ban if one was banned

**Comment by Grover-c13** [comment]
can you provide some sample HIDs?

**Comment by realmbmc** [comment]
9d2889452144f34d37a926c9017ae16bf46d4da0

5 different players has this same hwid

**Comment by Grover-c13** [comment]
Hmmm, this shouldnt happen. hash collisions for SHA1 are very low. Its more likely they are using modified games/cheats with hardware id set to something static. 

Do you know what os they were on?

**Comment by Grover-c13** [comment]
And just to add, its unity that calculates the hardware id: 
Windows Standalone: returns a hash from the concatenation of strings taken from Computer System Hardware Classes (https://msdn.microsoft.com/en-us/library/windows/desktop/aa389273(v=vs.85).aspx): 
Win32_BaseBoard::SerialNumber 
Win32_BIOS::SerialNumber 
Win32_Processor::UniqueId 
Win32_DiskDrive::SerialNumber 
Win32_OperatingSystem::SerialNumber
