### ISSUE TITLE
Multiadmin doesnt start

### ISSUE THREAD

**Issue by Draakoor** [Grover-c13/MultiAdmin#143]
My Multiadmin doesn't start.
It crashes after starting
Startlog on dedicated server:
[10:36:45] Config file located at: C:\Users\Administrator\AppData\Roaming/SCP S
cret Laboratory/config.txt

Unbehandelte Ausnahme: System.ArgumentOutOfRangeException: Die Länge darf nicht
kleiner als 0 (null) sein.
Parametername: length
   bei System.String.Substring(Int32 startIndex, Int32 length)
   bei MultiAdmin.Config.Reload()
   bei MutliAdmin.Program.StartHandleConfigs(String[] args)
   bei MutliAdmin.Program.Main(String[] args)

**Comment by Grover-c13** [comment]
Somethings wrong in your config, post it please.

**Comment by Draakoor** [comment]
GAME SETTINGS:
minimum_MTF_time_to_spawn = 280;
maximum_MTF_time_to_spawn = 350;
ci_respawn_percent = 35;
ci_on_start_percent = 10;
team_respawn_queue = 40143140314414041340;
server_forced_class = -1; (-1 = random)
map_seed = -1; (-1 = random)
intercom_cooldown = 120;
intercom_max_speech_time = 60;
auto_round_restart_time = 10;
friendly_fire = true;

///////////////////////////////////

THESE SETTINGS REQUIRES THE GAME TO RESTART:
server_ip = 81.169.213.179;
server_name = [GER/EN]GGU-Foundation[24/7];
ban_database_folder = [appdata]/SCP Secret Laboratory/Bans;

administrator_password = secretly;
THE PROJECT OWNERS  (HUBERT MOSZKA & WESLEY VAN VELSEN) RESERVE THE RIGHT TO OVERRIDE ACCESS TO THE REMOTE ADMIN PANEL

allow_scpsl_staff_to_use_remoteadmin = true;
IF TRUE - THE ENTIRE SCP: SECRET LABORATORY STAFF WILL BE ABLE TO USE REMOTE ADMIN PANEL

port_queue = 7777;
serverinfo_pastebin_id = UEAg9AxJ;

max_players = 25;

allow_project_manager_remote_admin = true;

**Comment by Grover-c13** [comment]
remove
THE PROJECT OWNERS (HUBERT MOSZKA & WESLEY VAN VELSEN) RESERVE THE RIGHT TO OVERRIDE ACCESS TO THE REMOTE ADMIN PANEL
and 
IF TRUE - THE ENTIRE SCP: SECRET LABORATORY STAFF WILL BE ABLE TO USE REMOTE ADMIN PANEL

**Comment by SlenderPlays** [comment]
If you wish to type something that is not a config, use // before every line. And also I reccomend when you are done editing configs, make a backup of it and the original edit it so it has no comments.

When you wish to edit it again, edit the backup and use the backup and when you are done with that do the same.

If you are not experiencing any more issues please notify us.

Note to devs: Close the issue within 7 days, no more reply so most likely it worked.

**Comment by Dankrushen** [comment]
No further responses, we'd need some sort of explanation on how to reproduce this bug. This is most likely fixed in the newer versions anyways.
