### ISSUE TITLE
$warhead_detonated does not display correctly

### ISSUE THREAD

**Issue by PatPeter** [Grover-c13/MultiAdmin#145]
As you can see in [this screenshot](https://i.imgur.com/rhhtSks.jpg), I'm using $warhead_detonated in my server name and it does display when the warhead goes off, but the symbols draw as ? instead of ☢. I have other Unicode drawing in my server name, so it doesn't seem to be a Unicode issue.

**Comment by Dankrushen** [comment]
The text was input wrong in the code, I'll re-upload the latest release with that fixed

**Comment by Dankrushen** [comment]
Done, re-download the release from https://github.com/Grover-c13/MultiAdmin/releases/tag/SM1.7.5 and it should be fixed

**Comment by PatPeter** [comment]
Thanks!
