### ISSUE TITLE
NEW <config_id> doesn't work!

### ISSUE THREAD

**Issue by realmbmc** [Grover-c13/MultiAdmin#16]
MultiAdmin command NEW <config_id> doesn't work. Server doesn't swap config.
Also if you just start MultiAdmin with few config_ids in servers folder nothing happens after server initialization. Server doesn't swap config files and starts just one server.

**Comment by Grover-c13** [comment]
NEW will work if you delete your spc_multiadmin.cfg, as i said not something you should be using.

https://github.com/Grover-c13/MultiAdmin/releases/tag/MA1.2
this will fix the auto startup issue.
