### ISSUE TITLE
MultiAdmin 2.0.0 Bans Nonfunctional with No Console Logs

### ISSUE THREAD

**Issue by PatPeter** [Grover-c13/MultiAdmin#165]
I am getting this error on **every single ban** that I've tried to create since thew 

    The process has occurred an issue! Failures: 1
    Last error log:
    Error: Code: good

If I check the output logs on my server, there is no exception listed explaining why bans aren't working. Here's what it looks like in the admin console:

https://steamcommunity.com/sharedfiles/filedetails/?id=1396635800

**Comment by PatPeter** [comment]
@Dankrushen I know this has nothing to do with MultiAdmin, but does it have nothing to do with ServerMod2 2 as well? It's saying that there's an error coming back from the server.

**Comment by Dankrushen** [comment]
It's a game bug
