### ISSUE TITLE
FATAL ERROR: Adding a space after an admin role prevents allocation of ports

### ISSUE THREAD

**Issue by PatPeter** [Grover-c13/MultiAdmin#167]
This is going to sound like complete hyperbole, but I've spent hour and a half from 9:27pm until now debugging this and trying to fix this issue.

Two of my servers, #1 and #4, crashed two hours ago. To try fixing them, I killed the processes and let them restart. They didn't show up in the server list after killing them multiple times. Finally, I killed the whole server stack in an attempt to fix it.

After I killed the whole server stack, the first thing I did was verify game cache with SteamCMD. I did this, redownloaded Assembly-CSharp and Smod2 to the latest versions, and restarted the stack.
It still didn't work.
I updated MultiAdmin to the latest version.
It still didn't work.
I moved my SCP installation folder to a new directory and downloaded a fresh copy.
It still didn't work.

Finally, I moved my "SCP Secret Laboratory" folder out of my .config directory, and it worked! I moved files one-by-one (SteamIdBans.txt, IpBans.txt, etc.) until I isolated it down to the `config_remoteadmin.txt` file.

I thought it might be an invalid character in my admin password, so I set it back to none. I set `override_password_role` to owner instead of admin. Finally, I removed my whole admin list except for myself, and it worked!!!

I added back my entire list of admins from backup, and started removing them one-by-one from the bottom up. Finally, I downloaded the file to Windows and opened it in Notepad2...

![Can you see the space that caused this error?](https://i.imgur.com/0tEUI9G.png)

It was a single space. A single space character made my server incapable of instantiating a socket for port 7777, 7778, or any other port for that matter.

**Comment by PatPeter** [comment]
Actually, it might have been the newline at the end of the file. Newline or space, one of the two.

**Comment by Dankrushen** [comment]
This isn't a problem with MultiAdmin, this would be for ServerMod https://github.com/Grover-c13/Smod2
