### ISSUE TITLE
Smod titlebar check is not great

### ISSUE THREAD

**Issue by Grover-c13** [Grover-c13/MultiAdmin#169]
https://github.com/Grover-c13/MultiAdmin/blob/master/mutliadmin/MultiAdmin/OutputThread.cs#L216

Needs to be changed to if (gameMessage.Contains("ServerMod - Version")) and moved to a constant.

Right now servermod exceptions  mess up the titlebar and can cause MA to crash.

**Comment by Dankrushen** [comment]
In extension, I'd suggest creating a new system for checking the messages and handling the events, the current one is very prone to errors
