### ISSUE TITLE
Too many heap sections.

### ISSUE THREAD

**Issue by realmbmc** [Grover-c13/MultiAdmin#17]
After a certain time servers are crashed with error:
Too many heap sections.

Also NEW <config_id> creates new server instance with ID 1 always.
Running latest MultiAdmin and servermod

**Comment by ADrySoldier** [comment]
Also have this error, possibly a memory leak?

**Comment by Grover-c13** [comment]
Yeah its a memory leak, im having trouble tracking it down.

Ive just fixed multiadmin to automatically restart on low memory:
https://github.com/Grover-c13/MultiAdmin/releases/tag/MA1.2.1
