### ISSUE TITLE
Server round refusing to restart using `roundrestart` command.

### ISSUE THREAD

**Issue by KcrPL** [Grover-c13/MultiAdmin#171]
Hi,

There is one major problem with MultiAdmin. When typing in `roundrestart` command - nothing happens.

>[01:22:47] >>> roundrestart
[01:22:47] Sending request to SCP: Secret Laboratory...
[01:22:49] The round is about to restart! Please wait..

That's it - after that, nothing happens. I have to reset the server manually.

EDIT: Upon exiting, it tells me something about 5 exceptions.

Hopefully I'll get answered soon! :)

Cheers,
KcrPL.

**Comment by Dankrushen** [comment]
This isn't a MultiAdmin problem, this would be a ServerMod problem https://github.com/Grover-c13/Smod2

**Comment by KcrPL** [comment]
Ah, I see. I also want to say that I opened this issue 2 months ago and I had this problem, last time when I used the server (`which was about 1 or 2 weeks ago`) everything was ok, so I guess we can close this issue once and for all.
