### ISSUE TITLE
Add \r\n config.txt line endings detection because \n breaks servers

### ISSUE THREAD

**Issue by PatPeter** [Grover-c13/MultiAdmin#177]
After using a config generation script, much to my dismay, I learned that if the config.txt files have their line endings replaced with \n from \r\n, it will cause the void glitch issue every time servers restart:

https://clips.twitch.tv/HumbleGoodEggplantAsianGlow
https://clips.twitch.tv/HonestAbstruseDunlinKevinTurtle
https://clips.twitch.tv/GlamorousSaltyJayLitFam

This seems to be an issue in vanilla SCP, but at least if server owners are using MultiAdmin, then MultiAdmin can warn them that their config files are corrupt.

**Comment by KarlOfDuty** [comment]
I feel like it's up to you to keep proper line endings for your os.

**Comment by PatPeter** [comment]
"Proper line endings" for Linux are \n. Are you saying I should set all of my configuration files to "\n" on Linux despite the fact that it would cause this bug?

**Comment by Dankrushen** [comment]
All my line endings on Linux are `\n` and it works fine...

**Comment by PatPeter** [comment]
This same problem is present in the new update, but I think I just found the problem!

**Comment by Dankrushen** [comment]
This problem should be fixed with my pull request (#199).
