### ISSUE TITLE
Multiadmin creates a server folder called 0 from time to time with only log files in it

### ISSUE THREAD

**Issue by KarlOfDuty** [Grover-c13/MultiAdmin#180]

**Comment by Dankrushen** [comment]
Is this still an issue?

**Comment by KarlOfDuty** [comment]
Yes.

**Comment by Dankrushen** [comment]
What's in your config?
Have you tried my 3.0.0 test version on Discord?

**Comment by KarlOfDuty** [comment]
I have not tried 3.0.0, I don't use any custom MA config settings.

**Comment by Dankrushen** [comment]
Can you list the name of the subdirectories within your servers folder? I'm wondering if you have a space or something that could possibly cause the name to be read wrong?

**Comment by KarlOfDuty** [comment]
![image](https://user-images.githubusercontent.com/18099825/52580069-dd206200-2e27-11e9-80e1-4976eecd0d3b.png)

**Comment by Dankrushen** [comment]
I'm not sure if the text file being there would cause issue, I'd definitely suggest trying my MultiAdmin 3.0.0 version
