### ISSUE TITLE
Errors spam

### ISSUE THREAD

**Issue by realmbmc** [Grover-c13/MultiAdmin#19]
After latest update I have this error spamming:

> NullReferenceException
>   at (wrapper managed-to-native) UnityEngine.Animator:SetTriggerString (string)
>   at UnityEngine.Animator.SetTrigger (System.String name) [0x00000] in <filename unknown>:0 
>   at AnimationController.DoAnimation (System.String trigger) [0x00000] in <filename unknown>:0 
>   at WeaponManager.RpcSyncAnim (System.String triggername) [0x00000] in <filename unknown>:0 
>   at WeaponManager.InvokeRpcRpcSyncAnim (UnityEngine.Networking.NetworkBehaviour obj, UnityEngine.Networking.NetworkReader reader) [0x00000] in <filename unknown>:0 
>   at UnityEngine.Networking.NetworkIdentity.HandleRPC (Int32 cmdHash, UnityEngine.Networking.NetworkReader reader) [0x00000] in <filename unknown>:0 
>   at UnityEngine.Networking.ClientScene.OnRPCMessage (UnityEngine.Networking.NetworkMessage netMsg) [0x00000] in <filename unknown>:0 
>   at UnityEngine.Networking.NetworkConnection.InvokeHandler (UnityEngine.Networking.NetworkMessage netMsg) [0x00000] in <filename unknown>:0 
>   at UnityEngine.Networking.LocalClient.ProcessInternalMessages () [0x00000] in <filename unknown>:0 
>   at UnityEngine.Networking.LocalClient.Update () [0x00000] in <filename unknown>:0 
>   at UnityEngine.Networking.NetworkClient.UpdateClients () [0x00000] in <filename unknown>:0 
>   at UnityEngine.Networking.NetworkIdentity.UNetStaticUpdate () [0x00000] in <filename unknown>:0 
>  
> (Filename:  Line: -1)

And this:

> NullReferenceException: Object reference not set to an instance of an object
>   at RadioInitializator.LateUpdate () [0x00000] in <filename unknown>:0 
>  
> (Filename:  Line: -1)

One more error:

> IndexOutOfRangeException: Array index is out of range.
>   at Dissonance.Networking.PacketWriter.Write (Byte b) [0x00000] in <filename unknown>:0 
>   at Dissonance.Networking.PacketWriter.Write (UInt16 u) [0x00000] in <filename unknown>:0 
>   at Dissonance.Networking.PacketWriter.WriteHandshakeResponse[HlapiConn] (UInt32 session, UInt16 clientId, Dissonance.Networking.ClientIdCollection idMap, System.Collections.Generic.Dictionary`2 peersByRoom) [0x00000] in <filename unknown>:0 
>   at Dissonance.Networking.Server.BroadcastingClientCollection`1[Dissonance.Integrations.UNet_HLAPI.HlapiConn].ProcessHandshakeRequest (HlapiConn source, Dissonance.Networking.PacketReader& reader) [0x00000] in <filename unknown>:0 
>   at Dissonance.Networking.BaseServer`3[Dissonance.Integrations.UNet_HLAPI.HlapiServer,Dissonance.Integrations.UNet_HLAPI.HlapiClient,Dissonance.Integrations.UNet_HLAPI.HlapiConn].NetworkReceivedPacket (HlapiConn source, ArraySegment`1 data) [0x00000] in <filename unknown>:0 
>   at Dissonance.Integrations.UNet_HLAPI.HlapiServer.OnMessageReceivedHandler (UnityEngine.Networking.NetworkMessage netmsg) [0x00000] in <filename unknown>:0 
>   at UnityEngine.Networking.NetworkConnection.HandleReader (UnityEngine.Networking.NetworkReader reader, Int32 receivedSize, Int32 channelId) [0x00000] in <filename unknown>:0 
>   at UnityEngine.Networking.NetworkConnection.HandleBytes (System.Byte[] buffer, Int32 receivedSize, Int32 channelId) [0x00000] in <filename unknown>:0 
>   at UnityEngine.Networking.NetworkConnection.TransportReceive (System.Byte[] bytes, Int32 numBytes, Int32 channelId) [0x00000] in <filename unknown>:0 
>   at UnityEngine.Networking.NetworkServer.OnData (UnityEngine.Networking.NetworkConnection conn, Int32 receivedSize, Int32 channelId) [0x00000] in <filename unknown>:0 
>   at UnityEngine.Networking.NetworkServer+ServerSimpleWrapper.OnData (UnityEngine.Networking.NetworkConnection conn, Int32 receivedSize, Int32 channelId) [0x00000] in <filename unknown>:0 
>   at UnityEngine.Networking.NetworkServerSimple.HandleData (Int32 connectionId, Int32 channelId, Int32 receivedSize, Byte error) [0x00000] in <filename unknown>:0 
>   at UnityEngine.Networking.NetworkServerSimple.Update () [0x00000] in <filename unknown>:0 
>   at UnityEngine.Networking.NetworkServer.InternalUpdate () [0x00000] in <filename unknown>:0 
>   at UnityEngine.Networking.NetworkServer.Update () [0x00000] in <filename unknown>:0 
>   at UnityEngine.Networking.NetworkIdentity.UNetStaticUpdate () [0x00000] in <filename unknown>:0 
>  
> (Filename:  Line: -1)

**Comment by Grover-c13** [comment]
This is a regression from the update, im yet to go back and put all my old changes into the new version such as the null reference checks.

**Comment by Grover-c13** [comment]
Fixed in latest ServerMod
