### ISSUE TITLE
Fix the SCPSL.exe process being left on if you close MultiAdmin during startup on windows

### ISSUE THREAD

**Issue by KarlOfDuty** [Grover-c13/MultiAdmin#190]

**Comment by Dankrushen** [comment]
This is probably not fixable through MultiAdmin, I'm not sure what could be changed to fix this problem as MultiAdmin already tries to kill the game process when exiting.

**Comment by KarlOfDuty** [comment]
Fair enough.

**Comment by Dankrushen** [comment]
The `EXIT` command should properly kill the server now when it's starting up in #200
