### ISSUE TITLE
E-mail in console

### ISSUE THREAD

**Issue by kotykk** [Grover-c13/MultiAdmin#193]
Hello, I've seen a problem with e-mails and "@" letter on MultiAdmin console

Image:
![image](https://user-images.githubusercontent.com/35780035/50016687-2ee47180-ffca-11e8-9585-d54d3cf93953.png)

**Comment by Dankrushen** [comment]
Unable to reproduce, please re-open if this is still an issue

**Comment by kotykk** [comment]
Look at the date 😆 

I think you fixed it anyway ;p
