### ISSUE TITLE
multiadmin takes 20 seconds to restart server

### ISSUE THREAD

**Issue by wasteofspace4023** [Grover-c13/MultiAdmin#195]
At the end of every regular-length match, [this](https://i.imgur.com/G9D9in8.png) happens. I'm unsure as to whether the "Game engine exited/crashed/closed/restarting" is supposed to happen, but it causes multiadmin to completely restart, taking ~20 seconds to get back online. Way too long. Thanks in advance.

**Comment by Dankrushen** [comment]
This is completely normal behaviour, any idea why it restarts every round? It seems like it'd most likely by your configuration.
