### ISSUE TITLE
Crash on windows server startup

### ISSUE THREAD

**Issue by realmbmc** [Grover-c13/MultiAdmin#2]
Our dedicated server is restarting every 24 hours. I've created sheduled task to exec my batch that starts steam client and after 30 seconds starts MultiAdmin.exe but all my 3 servers are crashing with this reason:

> [2018-02-02 04:33:18] The game engines working memory was too low for more than 5 ticks.

Also whenever I try to start MultiAdmin.exe using windows sheduler it uses windows\system32 folder as default...

Here's a batch file:

> cd "C:\SteamLibrary\steamapps\common\SCP Secret Laboratory"
start MultiAdmin.exe

After manual restart everything is working good. We have 24gb DDR4 memory, 3 servers on different ports are using ~3gb.
I don't know if it's a game's bug or MultiAdmin bug but I hope you can help us to fix this issue. Thanks!

**Comment by Grover-c13** [comment]
In theory id imagine the same thing happens with LocalAdmin (the code is taken directory from there). Ill probably be adding a setting to disable the automatic memory restart in the next version (or increasing the tick length).

**Comment by realmbmc** [comment]
Thanks!

**Comment by Grover-c13** [comment]
Hi, the new version has a new config setting:
shutdown_low_memory, setting this to 0 or lower should stop it.

https://github.com/Grover-c13/MultiAdmin/releases/tag/1.0
