### ISSUE TITLE
Voice chat issue is still here...

### ISSUE THREAD

**Issue by realmbmc** [Grover-c13/MultiAdmin#20]
After all that long waiting voice chat is getting scrambled,
Nickname of talking player is wrong and spectators can hear alive players at all distance.
Probably because of increasing players count more than 20

**Comment by Grover-c13** [comment]
This is a regression from the update, will put the network tweaked settings back in next version.

**Comment by realmbmc** [comment]
Newest version of game and servermod/multiadmin still has voice chat issue. Even more: now somehow alive class D and scientists can hear SCPs.
