### ISSUE TITLE
restart_low_memory: -1 not disabling hard restart

### ISSUE THREAD

**Issue by storm37000** [Grover-c13/MultiAdmin#204]
`restart_low_memory: -1` in the `scp_multiadmin.cfg` config file not disabling hard restart.  I only want soft round end restart enabled.  Setting this to a high negative number seems to be the only way to "disable" it.

**Comment by Dankrushen** [comment]
Fixed in v3.1.0, once that releases, it should be working.

**Comment by Dankrushen** [comment]
Closing because this should be fixed, please re-open if you find the latest test version available on the Discord still has this issue, the release #206 is planned to happen soon.
