### ISSUE TITLE
Engine console spam being output to MA, causing it to crash when typing.

### ISSUE THREAD

**Issue by storm37000** [Grover-c13/MultiAdmin#205]
Engine console spam being output to MA, causing it to crash when typing.  This happens when nolog is true,  and i have fixed these in my own branch before by adding `-logFile /dev/null` for linux and `-logFile NUL` for windows to the start args for scpsl.

**Comment by Dankrushen** [comment]
Closing because this should be fixed, please re-open if you find the latest test version available on the Discord still has this issue, the release #206 is planned to happen soon.
