### ISSUE TITLE
MultiAdmin still reads SteamIDWhitelist.txt from [appdata], not servers directory

### ISSUE THREAD

**Issue by PatPeter** [Grover-c13/MultiAdmin#209]
I switched `enable_whitelist` to true in my config.txt and putting SteamIDWhitelist.txt in the same directory as my server, and it had no effect. I had to set the whitelist in the [appdata] folder in order for it to take effect.

**Comment by Dankrushen** [comment]
Check out the `share_non_configs` config option, it's probably the reason for this behaviour.

**Comment by Dankrushen** [comment]
Closed due to inactivity, please re-open if you still have this problem.

**Comment by PatPeter** [comment]
Yeah don't worry about it. Whitelist takes too much effort for me to keep up-to-date so I'm not using it anymore.
