### ISSUE TITLE
Server is crashing after certain time

### ISSUE THREAD

**Issue by realmbmc** [Grover-c13/MultiAdmin#21]
Log:

> OutOfMemoryException: Out of memory
>   at (wrapper managed-to-native) object:__icall_wrapper_mono_array_new_specific (intptr,int)
>   at System.Array.Resize[InternalMsg] (.InternalMsg[]& array, Int32 length, Int32 newSize) [0x00000] in <filename unknown>:0 
>   at System.Array.Resize[InternalMsg] (.InternalMsg[]& array, Int32 newSize) [0x00000] in <filename unknown>:0 
>   at System.Collections.Generic.Stack`1[UnityEngine.Networking.LocalClient+InternalMsg].Push (InternalMsg t) [0x00000] in <filename unknown>:0 
>   at UnityEngine.Networking.LocalClient.ProcessInternalMessages () [0x00000] in <filename unknown>:0 
>   at UnityEngine.Networking.LocalClient.Update () [0x00000] in <filename unknown>:0 
>   at UnityEngine.Networking.NetworkClient.UpdateClients () [0x00000] in <filename unknown>:0 
>   at UnityEngine.Networking.NetworkIdentity.UNetStaticUpdate () [0x00000] in <filename unknown>:0 
>  
> (Filename:  Line: -1)
> 
> ========== OUTPUTING STACK TRACE ==================
> 
> 0x74F549A2 (KERNELBASE) DebugBreak
> 0x1010C966 (mono) mono_unity_class_get
> 0x1010CEAC (mono) mono_unity_class_get
> 0x1010BE5A (mono) mono_unity_class_get
> 0x1010C098 (mono) mono_unity_class_get
> 0x1010C1F6 (mono) mono_unity_class_get
> 0x1005F437 (mono) mono_array_new_specific
> 0x04980533 (Mono JIT Code) (wrapper managed-to-native) object:__icall_wrapper_mono_array_new_specific (intptr,int)
> 0x04A1F345 (Mono JIT Code) System.Array:Resize<UnityEngine.Networking.LocalClient/InternalMsg> (UnityEngine.Networking.LocalClient/InternalMsg[]&,int,int)
> 0x04A1F2E3 (Mono JIT Code) System.Array:Resize<UnityEngine.Networking.LocalClient/InternalMsg> (UnityEngine.Networking.LocalClient/InternalMsg[]&,int)
> 0x04A1F25A (Mono JIT Code) System.Collections.Generic.Stack`1<UnityEngine.Networking.LocalClient/InternalMsg>:Push (UnityEngine.Networking.LocalClient/InternalMsg)
> 0x04A231AB (Mono JIT Code) UnityEngine.Networking.LocalClient:ProcessInternalMessages ()
> 0x04A23049 (Mono JIT Code) UnityEngine.Networking.LocalClient:Update ()
> 0x049D2A5A (Mono JIT Code) UnityEngine.Networking.NetworkClient:UpdateClients ()
> 0x049D2940 (Mono JIT Code) UnityEngine.Networking.NetworkIdentity:UNetStaticUpdate ()
> 0x04980263 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void (object,intptr,intptr,intptr)
> 0x100F2236 (mono) mono_set_defaults
> 0x1005DCA5 (mono) mono_runtime_invoke
>   ERROR: SymGetSymFromAddr64, GetLastError: 'Попытка обращения к неверному адресу.' (Address: 5522F30F)
> 0x5522F30F (UnityPlayer) (function-name not available)
>   ERROR: SymGetSymFromAddr64, GetLastError: 'Попытка обращения к неверному адресу.' (Address: 5522AD09)
> 0x5522AD09 (UnityPlayer) (function-name not available)
>   ERROR: SymGetSymFromAddr64, GetLastError: 'Попытка обращения к неверному адресу.' (Address: 55424F63)
> 0x55424F63 (UnityPlayer) (function-name not available)
>   ERROR: SymGetSymFromAddr64, GetLastError: 'Попытка обращения к неверному адресу.' (Address: 551517DA)
> 0x551517DA (UnityPlayer) (function-name not available)
>   ERROR: SymGetSymFromAddr64, GetLastError: 'Попытка обращения к неверному адресу.' (Address: 555D221E)
> 0x555D221E (UnityPlayer) (function-name not available)
> 0x555D2445 (UnityPlayer) UnityMain
>   ERROR: SymGetSymFromAddr64, GetLastError: 'Попытка обращения к неверному адресу.' (Address: 00ED1275)
> 0x00ED1275 (SCPSL) (function-name not available)
>   ERROR: SymGetSymFromAddr64, GetLastError: 'Попытка обращения к неверному адресу.' (Address: 00ED1437)
> 0x00ED1437 (SCPSL) (function-name not available)
> 0x754762C4 (KERNEL32) BaseThreadInitThunk
> 0x77A60F79 (ntdll) RtlSubscribeWnfStateChangeNotification
> 0x77A60F44 (ntdll) RtlSubscribeWnfStateChangeNotification
> 
> ========== END OF STACKTRACE ===========

**Comment by Grover-c13** [comment]
This is a bug with the game, i cant really fix it unless i can find the source of the memory leak, which is not a practical task with out the original unity project.
