### ISSUE TITLE
MA 3.1.1+ creates two consoles on Linux, splits input for each server

### ISSUE THREAD

**Issue by PatPeter** [Grover-c13/MultiAdmin#212]
So I tried to type help after bringing up a server with MultiAdmin 3.1.2, I typed it ONCE and this happened:

```
> help
CLASSLIST <page>: Prints a list of classes and their IDs
CLEAN [Item ID]...: Removes all found instances of specified items (Supports multiple separated by spaces or no args for all items).
CLEARBROADCASTS/BCCLEAR/CLEARBC/CLEARALERT/ALERTCLEAR: Clears the queue of messages to broadcast to players
[20:39:01] ServerMod - Version 3.4.0-A
[20:39:01] SCP:SL - Version 8.0.1 (Revision III)
[20:39:01] Failed to split ports.
[20:39:01] Scene Manager: Loaded scene 'FastMenu' [Assets/_Scenes/FastMenu.unity]
> help
Flash <Player(s)|All>: Throws a flash-bang at specified player/players.
GIVE <id>: Gives the player an item (doesnt work with dedicated servers)
```

It's hard to describe without a video, but basically it was doing this:

```
> h
> 
> h
> h
> he
> h
> he
> he
> hel
> he
> hel
> hel
> help
> hel
> help
> help
```

So yes, I had to type "hheellpp" to type help on one of my servers. If I type it normally, it only types "hl".

**Comment by Dankrushen** [comment]
Yes, that's because you started two servers in one console window, you have to start them separately. For info, check [the execution arguments](https://github.com/Grover-c13/MultiAdmin#multiadmin-execution-arguments).

**Comment by PatPeter** [comment]
Ah, I thought this part of the documentation was a hold-over from MultiAdmin 2.x. Sorry about that! I'll try running it again today.

> Support for running multiple server instances in one MultiAdmin instance

**Comment by PatPeter** [comment]
Honestly now that I think about it, the simplest solution to #151 was to just split MultiAdmin to only support 1 instance of SCP:SL at a time, not running all the servers through one executable. Now it works like all other game servers do and I'm hoping it's more stable. Thanks for the reply!
