### ISSUE TITLE
Assigning an invalid group to a moderator will prevent the server from starting

### ISSUE THREAD

**Issue by PatPeter** [Grover-c13/MultiAdmin#214]
If you set an admin to an admin role that is not specified in Roles, the server will not start. I had a typo in my config_remoteadmin.txt and this typo completely prevented my servers from loading.

**Comment by Dankrushen** [comment]
Not related to MultiAdmin, sounds like a main game bug

**Comment by PatPeter** [comment]
Ah, I had `disable_config_validation: true` set in my scp_multiadmin.cfg and thought that this was a bug because it didn't disable config validation. Sorry again @Dankrushen!
