### ISSUE TITLE
Disable moving config file to LEGANCY CONFIG BACKUP - NOT WORKING.txt

### ISSUE THREAD

**Issue by PatPeter** [Grover-c13/MultiAdmin#215]
I cannot find code that moves this file in the MultiAdmin or ServerMod2 repositories, so please forgive me if this issue is in the wrong repo.

I use a script called MergeConfigs.sh to merge my scripts together. Creation of the LEGANCY(?) file is screwing up my workflow for deploying configs to my servers.

**Comment by Dankrushen** [comment]
Again, MultiAdmin does not touch any of your configs other than `scp_multiadmin.cfg`, this is a main game issue that could most likely be resolved in ServerMod.

**Comment by PatPeter** [comment]
Sorry about that!
