### ISSUE TITLE
Multiadmin dont restart 

### ISSUE THREAD

**Issue by danya201272** [Grover-c13/MultiAdmin#219]
![image](https://user-images.githubusercontent.com/36302863/65385576-0e0b3280-dd39-11e9-8d08-f64eb7e41e4a.png)

**Comment by realmbmc** [comment]
I've had similar issue with newest build. As soon as I connect to my windows server using RDP, it seems that servers are going to restart immediately after multiadmin window expand. This is very strange and I didn't had any issues like that with 3.2.1 build.

**Comment by Dankrushen** [comment]
Can you try this build?
[MultiAdmin.zip](https://github.com/Grover-c13/MultiAdmin/files/3640057/MultiAdmin.zip)
(Sorry it's a ZIP, GitHub doesn't accept EXEs)

**Comment by danya201272** [comment]
Ok i try now

**Comment by danya201272** [comment]
I have server in windows server 2012

**Comment by danya201272** [comment]
> Can you try this build?
> [MultiAdmin.zip](https://github.com/Grover-c13/MultiAdmin/files/3640057/MultiAdmin.zip)
> (Sorry it's a ZIP, GitHub doesn't accept EXEs)

Its work and restart.What are you doing?

**Comment by Dankrushen** [comment]
That's unfortunate, oh well, I'll commit it and upload a new release

**Comment by Dankrushen** [comment]
Actually, before I do anything, can you tell me what version of .NET you're running?

**Comment by danya201272** [comment]
> Actually, before I do anything, can you tell me what version of .NET you're running?

My plugin use net.fraemwork 4.7.1 and smod 3.5.0

**Comment by danya201272** [comment]
I try use your multiadmin with smod 3.5.1-d

**Comment by Dankrushen** [comment]
Not your plugin, what version of .NET do you have on your server

**Comment by danya201272** [comment]
What your recommend version?

**Comment by Dankrushen** [comment]
Closing due to the issue having been resolved
