### ISSUE TITLE
Grenades doesn't make any damage

### ISSUE THREAD

**Issue by realmbmc** [Grover-c13/MultiAdmin#23]
Since I've installed latest version of servermod grenades doesn't make any damage.

**Comment by kotyk-pl** [comment]
It can be friendly-fire setting. When you drop grenade to lift, that when exploding don`t have damage (it can be friendly-fire setting) When you drop grenade to SCP feet and that don`t giving damage, it`s a error

**Comment by realmbmc** [comment]
Yeah, my fault. Closed
