### ISSUE TITLE
Suggestion - Add SCP172_HP

### ISSUE THREAD

**Issue by E-v-o** [Grover-c13/MultiAdmin#25]
**Date:**
10/02/2018

**Feature:**
SC172_HP

**Reason:**
Since the recent update to the game, I feel that lowering the SCP's health tends to balance the rounds a little more. Also, it seems at the moment 172 is the only SCP that hasn't been added, I'm not sure if this was intentional though.

**Comment by Grover-c13** [comment]
it is there as far as i know!

Setting is SCP173_HP default 2000

**Comment by realmbmc** [comment]
It's not SCP-172 but SCP-173.
Everything is working ok, I can confirg
