### ISSUE TITLE
Doors won't open with the new ServerMod version

### ISSUE THREAD

**Issue by ADrySoldier** [Grover-c13/MultiAdmin#26]
If the new servermod is updated, doors do not work at all. I tested this multiple times. I don't know if it's only my server. It's mostly the Class-D cell door, surface elevators, and heavy containment elevators.

**Comment by realmbmc** [comment]
Game was updated but not the servermod.

**Comment by Grover-c13** [comment]
Yeah, should be fixed on the latest release. I think there was a bit of confusion because i released an update a few hours before, that was for the original update and not the latest.
