### ISSUE TITLE
RESTART_LOW_MEMORY doesn't work

### ISSUE THREAD

**Issue by realmbmc** [Grover-c13/MultiAdmin#27]
RESTART_LOW_MEMORY = 100 doesn't work at latest version
My servers are crashing after some time with error:
Too many heap sections.
so they need to be restarted manually

**Comment by Grover-c13** [comment]
Memory can be messy, heap memory is a part of the total memory not all of it, and with the updated code from last release you may have to experiment to get the right value now.

For me heap errors happen at around 1000mb memory usage, so for me i should set RESTART_LOW_MEMORY to 2040 (the maximum amount of memory SPCSL can use) - 1000 (where the heap error occurs) = 1040 (as of the last version, before the code didnt really function how i thought it did, as it was taken from localadmin).

Currently on 100 its probably too low for it to reach it before the heap gets exhausted first.
