### ISSUE TITLE
Can I use this on Ubuntu Server?

### ISSUE THREAD

**Issue by Rikusen0335** [Grover-c13/MultiAdmin#38]
I wanna use this on Ubuntu Server, but linux beta just getting started.

**Comment by Grover-c13** [comment]
Yes

**Comment by Rikusen0335** [comment]
Is there anything special you have to do?

**Comment by Grover-c13** [comment]
you need to put a config file called spc_multiadmin.cfg next to MultiAdmin in the following format:
cfg_loc="locationtogameconfig.txt"; try avoid using the home ~ and use absolute paths.
