### ISSUE TITLE
Please build server_mod and multiadmin

### ISSUE THREAD

**Issue by realmbmc** [Grover-c13/MultiAdmin#4]
Could you please build server_mod and multiadmin and include to releases? Or just include in repo?

P.S. what did you use to decompile original game's code and what dlls I need to decompile to fully compile your server_mod?
I've used LSpy but it seems to make alot of mistakes. Thanks!

**Comment by Kipx** [comment]
just as an answer to your previous questions, the decompiler I believe he used is called dnSpy, located [here](https://github.com/0xd4d/dnSpy). In the meantime, Ill try to compile some code for you, just gimme a bit.

**Comment by realmbmc** [comment]
Thanks alot! I'll try it now

**Comment by realmbmc** [comment]
Now I don't get what should I decompile for recompiling Assembly-CSharp.dll with edits from server_mod.

**Comment by realmbmc** [comment]
Ok I've got it but now I don't understand how to modify PlayerStats class. What utility did you use? dnSpy can't edit it

**Comment by Grover-c13** [comment]
Ill be compiling and releasing a new version today, just be patient.

I dont recommend working with decompiled/recompiled code unless you know how. Some classes require using IL assembly which can easliy be stuffed up.

**Comment by Grover-c13** [comment]
https://github.com/Grover-c13/MultiAdmin/releases/tag/1.0
