### ISSUE TITLE
Update required

### ISSUE THREAD

**Issue by realmbmc** [Grover-c13/MultiAdmin#42]
As a newest game version (1.0.2) latest servermod seems to have alot of problems. It needs to be updated.
MultiAdmin is crashing. Seems like it can't get access to log file after restart because it is already using by another process (which is the pre-restart multiadmin).
https://i.imgur.com/5Y7JILG.png
Also this:
[02:53:57] Message printer warning: Could not open file SCPSL_Data\Dedicated\1518384247\sl724.mapi. Make sure that MultiAdmin.exe has all necessary read-write permissions.

It was running with admin privileges using direct shortcut with 1. 2 and 3 launch parameters
Like this:
"path\multiadmin.exe" 1

**Comment by E-v-o** [comment]
Download and build the latest version (the release hasn't been added yet). It's much more stable, haven't had a crash or issue so far and it's been around 12 hours.

**Comment by E-v-o** [comment]
Ah I see sorry! What I meant by my previous message was Grover has updated multiadmin but the build isn't on the release page but if you download the source and build it yourself it should solve most of the problems.

If it's easier for you I'm more than happy to send you it, message me on Discord my user is Evo#0822

**Comment by Grover-c13** [comment]
The build is there! it just doesnt show at the top since multiadmin is a version behind servermod.
https://github.com/Grover-c13/MultiAdmin/releases/tag/MA1.2.4
This fixes two crashes which i think will probably fix your isse @realmbmc
