### ISSUE TITLE
Suggestion - Moderation logs

### ISSUE THREAD

**Issue by E-v-o** [Grover-c13/MultiAdmin#43]
Date:
11/02/2018

Feature:
Log moderation (login to remote admin, kicks, bans and force class)

Reason:
I have a few players that I've entrusted the remote login on the server to help keep it clean from mic spammers etc, it would be nice to have logs to be sure the password isn't being shared out and they are not abusing it.

I'm aware Localadmin shows interaction in the console, is it possible to log them?

**Comment by realmbmc** [comment]
Also kill log would be awesome

**Comment by Grover-c13** [comment]
Latest release
