### ISSUE TITLE
Suggestion - Ban/Kick from console

### ISSUE THREAD

**Issue by E-v-o** [Grover-c13/MultiAdmin#44]
Date:
11/02/2018

Feature:
Ability to ban or kick from console

Reason:
As you host a server yourself you might be aware of the frustration of players making reports but you cannot join to actually do anything about it. I know you're limited to the functions of the game, so if it's not directly possible is there a way of maybe getting the player info, writing the file to the bans directory then reloading the ban list?

This would be an extremely helpful feature!

**Comment by realmbmc** [comment]
There is already BAN command.
Kicking is available using:
BAN nickname 0

**Comment by E-v-o** [comment]
Ah thanks! Wasn't even aware, I'll close this.
