### ISSUE TITLE
Latest update didn't solve voice chat issue

### ISSUE THREAD

**Issue by realmbmc** [Grover-c13/MultiAdmin#5]
After some time our players encount voice chat issue. We can't talk to each other.
Latest update didn't solve anything. But if it's fixed in ProfileStats class so I can't recompile it and can't test.

**Comment by Grover-c13** [comment]
Release here:
https://github.com/Grover-c13/MultiAdmin/releases/tag/1.0

If this doesnt help the issue im afraid we will have to wait until it fixed in the game :(
