### ISSUE TITLE
Admin panel still freezing sometimes

### ISSUE THREAD

**Issue by realmbmc** [Grover-c13/MultiAdmin#56]
After a certain time with unknown condition admin panel refuses to execute any admin's command.
Even BAN command doesn't output anything.
But HELP command at this state is working ok.
Using latest servermod/multiadmin. Probably game bug

**Comment by Grover-c13** [comment]
yeah its just the ban command as far as i can tell, MultiAdmin does everything right:
![image](https://user-images.githubusercontent.com/1520101/36109371-2a140720-105a-11e8-9e55-745b230a974b.png)

The commands get outputted, the game opens the file, it just doesnt do anything with it. Ill try to fix in the next version of servermod.

**Comment by realmbmc** [comment]
I was running server without multiadmin and I can confirm that ban system and remote admin panel works as intended. But as soon as I've installed MultiAdmin bug happened again.

**Comment by Grover-c13** [comment]
No its the game, you can recreate in local admin by:

1. hosting a game
2. Joining a game
3. leaving the game
4. typing ban

it still gets stuck.

**Comment by Grover-c13** [comment]
Ive reworked the command system for the game and decided to track down the issue at the same time. Good news is that its the same issue that causes remote admin to not function properly sometimes, so all of that should be fixed in 1.7 :D

**Comment by realmbmc** [comment]
Wow! The best news I've expected. Again thanks alot!
