### ISSUE TITLE
Since latest update my CPU load increased about 2-3 times!

### ISSUE THREAD

**Issue by realmbmc** [Grover-c13/MultiAdmin#6]
Now not only SCPSL process uses ~10% of CPU but even MultiAdmin uses 10-15% CPU power!
3 servers were using ~30-60% CPU but now at idle they use 90%. Please fix this issue! It is related to latest MultiAdmin.

**Comment by Grover-c13** [comment]
Should be fixed now:
https://github.com/Grover-c13/MultiAdmin/
