### ISSUE TITLE
Heap section issues

### ISSUE THREAD

**Issue by blizzard2023** [Grover-c13/MultiAdmin#62]
Hey Grover,

My servers keep crashing a lot from heap issues (and they don't restart when they do). Are you in the process of making a fix for this?

Thanks,
Blizzard

**Comment by Grover-c13** [comment]
Ive been trying to track down the memory leak, ive had no luck so far. Without unity tools its not practical. You can mess around with multiadmin setting to make the server restart when its memory is getting too low.

**Comment by blizzard2023** [comment]
I tried doing that - no luck. It crashes all the time.

**Comment by Grover-c13** [comment]
What do you have it set at? mine is set at RESTART_LOW_MEMORY=800;

Havent had a heap crash in days, you may have to expirement a bit to get the right value.

heap crashes happen for mat around ~1GB memory usage, so i took 2048-1000 and then took another 200 off just to give it a bit more wiggle room.

**Comment by blizzard2023** [comment]
So should I have it lower or higher than what you put?

**Comment by Grover-c13** [comment]
Try 800 and see how you go, if it still crashes due to heap error increase the number to 1000 and keep going up. It should never exceed ~1400 though. Please note this doesnt stop the leak, it just manages to restart the server before the heap error occurs which requires manual intervention.

**Comment by blizzard2023** [comment]
I did 1,000 and so far so good.

**Comment by blizzard2023** [comment]
Hi Grover, 

Just thought that I'd let you know the memory leaks I was experiencing was most likely due to my VPS. I am moving hosts, and getting a completely dedicated server thanks to the help from my community staff & members. With this new server I shouldn't have any more memory issues - but if I do I will certainly let you know.

Thanks for the help!
~ Blizzard
