### ISSUE TITLE
Any way to get server info by other programs?

### ISSUE THREAD

**Issue by ShingekiNoRex** [Grover-c13/MultiAdmin#68]
Hello.
I want to write a VC++ program which can get server info such as player count.
Is there any way to do that?

**Comment by Grover-c13** [comment]
You could build a class extending Feature and implementing the IEventPlayerConnect, IEventPlayerDisconnectIServerMod interfaces (use these to keep count of the players; also this interfaces require servermod installed). Build your thingo to DLL.

Then download the MultiAdmin source, add a reference to the DLL, add your feature class to Server.cs in the RegisterFeatures() method.

This is the easiest way i can think of doing it right now, but you will need a little bit of C# to register the feature. 

May look at adding some basic plugin functionality in future.
