### ISSUE TITLE
Crash on restart

### ISSUE THREAD

**Issue by realmbmc** [Grover-c13/MultiAdmin#78]
I am running latest version of MultiAdmin and Servermod.
After low-memory restart 2 of 3 servers are crashing.
Including screenshot:
https://i.imgur.com/KkWi0Hw.jpg
Ofcource there is a Dedicated folder

**Comment by Grover-c13** [comment]
Its been fixed (i think, coming in next release probably tomorrow)

**Comment by Grover-c13** [comment]
https://github.com/Grover-c13/MultiAdmin/releases/tag/MA1.2.5
