### ISSUE TITLE
SCP-173 can't move now. Blinking is disabled.

### ISSUE THREAD

**Issue by realmbmc** [Grover-c13/MultiAdmin#9]
SCP-173 can't move while players look at him. They don't blink now. That happened since latest update (servermod 1.0)

**Comment by E-v-o** [comment]
Also have the same issue. @realmbmc Can you share your config to check if it's something we both have?

**Comment by realmbmc** [comment]
> GAME SETTINGS:
> minimum_MTF_time_to_spawn = 360;
> maximum_MTF_time_to_spawn = 500;
> ci_respawn_percent = 30;
> ci_on_start_percent = 30;
> team_respawn_queue = xxxxxxxx;
> server_forced_class = -1; (-1 = random)
> map_seed = -1; (-1 = random)
> intercom_cooldown = 120;
> intercom_max_speech_time = 30;
> auto_round_restart_time = 30;
> friendly_fire = true;
> max_players = 20;
> RESTART_EVERY_NUM_ROUNDS = 10;
> no_scp079_first = true;
> SCP173_HP = 5000;
> SCP049-2_HP = 700;
> nuke_disable_cooldown = 80;
> SCP106_cleanup = yes;
> SCP457_DISABLE = yes;
> shutdown_low_memory = 0;
> 
> ///////////////////////////////////
> 
> THESE SETTINGS REQUIRES THE GAME TO RESTART:
> server_ip = auto;
> server_name = xxxxxx
> ban_database_folder = [appdata]/SCP Secret Laboratory/Bans;
> administrator_password = xxxxxx;
> port_queue = 7777;
> serverinfo_mode = info; (disabled - off, info - on)
> serverinfo_pastebin_id = 43HLxS2y;
>

**Comment by Kipx** [comment]
Just tested this as well, players are no longer blinking.

**Comment by Grover-c13** [comment]
Hi all,

Sorry! it was something i was testing and left it half baked in by accident :(

here is the fixed version https://github.com/Grover-c13/MultiAdmin/releases/tag/SM1.1
