### ISSUE TITLE
Server mod doesn't work ?

### ISSUE THREAD

**Issue by aGoodOldRub** [Grover-c13/MultiAdmin#91]
Hi

I installed the server mod and it works but when I use the max_players command it doesn't work on my server it doesn't let me go over 20 at all. I tried max_players 30;   max_players 30 and max_players = 30 none of them make any difference and I know it goes to 30 from other servers. Any info ?

**Comment by Grover-c13** [comment]
post your config

**Comment by Grover-c13** [comment]
also do you get a "ServerMod version 1.5" in the title or something similiar?

**Comment by aGoodOldRub** [comment]
Yes it says server mod 1.4 

GAME SETTINGS:
minimum_MTF_time_to_spawn = 200;
maximum_MTF_time_to_spawn = 300;
ci_respawn_percent = 35;
ci_on_start_percent = 10;
team_respawn_queue = 40143140314414041340;
server_forced_class = -1; (-1 = random)
map_seed = -1; (-1 = random)
intercom_cooldown = 100;
intercom_max_speech_time = 20;
auto_round_restart_time = 10;
friendly_fire = false;
max_players 30;
SCP106_HP 1500;
///////////////////////////////////

THESE SETTINGS REQUIRES THE GAME TO RESTART:
server_ip = 107.173.219.183;
server_name = [US] a good old rub | No Lag | No FF | $full_player_count $warhead_detonated  ;
ban_database_folder = [appdata]/SCP Secret Laboratory/Bans;
administrator_password = 19073169;
port_queue = 7777,7778,7779,7780,7781,7782,7783,7784;
serverinfo_pastebin_id = 7wV681fT;

**Comment by Grover-c13** [comment]
max_players = 30;

**Comment by aGoodOldRub** [comment]
Yeah, fixed the problem thanks :)
