### ISSUE TITLE
Using Servermod spawns you in Larry's spawn

### ISSUE THREAD

**Issue by laserman367** [Grover-c13/MultiAdmin#93]
Restarting the same, caused it to continue, switching back to the old Assembly file stopped it, switching back to the servermod file continued it even 5 hours later.

![20180222150516_1](https://user-images.githubusercontent.com/36745405/36562502-7ea3ae66-1817-11e8-9892-8d4f88e06ec3.jpg)
![20180222153746_1](https://user-images.githubusercontent.com/36745405/36562503-7ec1bb4a-1817-11e8-8d8d-abf9466fb7b5.jpg)

**Comment by Grover-c13** [comment]
Fixed
